name: Development Deployment

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Run tests
        run: |
          if [ -f package.json ]; then
            npm test
          fi

      - name: Deploy to GitHub Pages (Development)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: development
          publish_branch: gh-pages 